from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from io import BytesIO
import os

def generate_payslip_pdf(employee_name, employee_id, department, month, base_salary, deduction, final_salary):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=30, leftMargin=30, topMargin=30, bottomMargin=30)
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#1e1b4b"),
        alignment=1, # Center
        spaceAfter=20
    )
    
    header_style = ParagraphStyle(
        'HeaderStyle',
        parent=styles['Normal'],
        fontSize=12,
        textColor=colors.HexColor("#64748b"),
        alignment=1,
        spaceAfter=30
    )

    elements = []

    # 1. Add Logo if exists (with safety check)
    try:
        logo_path = os.path.join(os.getcwd(), "static", "logo.png")
        if os.path.exists(logo_path):
            img = Image(logo_path, width=80, height=80)
            img.hAlign = 'CENTER'
            elements.append(img)
            elements.append(Spacer(1, 10))
    except Exception as e:
        print(f"Logo loading failed: {e}")
        # Skip logo if it fails, don't crash the whole PDF
        pass

    # 2. Header
    elements.append(Paragraph("IET HRMS - OFFICIAL PAYSLIP", title_style))
    elements.append(Paragraph(f"Monthly Salary Statement for {month}", header_style))
    elements.append(Spacer(1, 20))

    # 3. Employee Info Table
    emp_data = [
        ["Employee Name:", employee_name, "Employee ID:", f"#{employee_id}"],
        ["Department:", department, "Period:", month],
    ]
    emp_table = Table(emp_data, colWidths=[100, 150, 100, 150])
    emp_table.setStyle(TableStyle([
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('TEXTCOLOR', (0,0), (0,-1), colors.HexColor("#475569")),
        ('TEXTCOLOR', (2,0), (2,-1), colors.HexColor("#475569")),
        ('BOTTOMPADDING', (0,0), (-1,-1), 12),
    ]))
    elements.append(emp_table)
    elements.append(Spacer(1, 40))

    # 4. Salary Breakdown Table
    data = [
        ["Description", "Amount"],
        ["Base Salary", f"Rs. {base_salary:,}"],
        ["Deductions (Absences)", f"- Rs. {deduction:,}"],
        ["", ""],
        ["Total Net Payable", f"Rs. {final_salary:,}"]
    ]
    
    salary_table = Table(data, colWidths=[350, 150])
    salary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f8fafc")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#1e293b")),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('LINEBELOW', (0, 0), (-1, 0), 1, colors.HexColor("#e2e8f0")),
        ('FONTNAME', (0, 4), (-1, 4), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 4), (-1, 4), 14),
        ('TEXTCOLOR', (1, 4), (1, 4), colors.HexColor("#10b981")),
        ('TOPPADDING', (0, 4), (-1, 4), 20),
    ]))
    elements.append(salary_table)

    # 5. Footer
    elements.append(Spacer(1, 100))
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey, alignment=1)
    elements.append(Paragraph("This is a computer-generated document and does not require a physical signature.", footer_style))
    elements.append(Paragraph("Generated by IET HRMS Portal", footer_style))

    doc.build(elements)
    buffer.seek(0)
    return buffer
